
=pod

=encoding utf8

=head1 Equinócio 2010 de Março !

É com o maior prazer que a B<São Paulo Perl Mongers> organiza um evento com
o objetivo de gerar conteúdo, agregar seus membros e compartilhar
conhecimentos.

A ideia surgiu baseado nos objetivos descritos acima, e procuramos uma
desculpa para justificar nossas metas de forma divertida, a solução surgiu e
ela foi baseada em um movimento do planeta terra com a estrela sol.

Equinócio é uma palavra derivada do latim, que significa "noite igual", no
qual é basicamente aos dois momentos do ano em que a duração do dia é
igual da noite sobre toda terra. (vide wikipedia,
L<http://pt.wikipedia.org/wiki/Equin%C3%B3cio>).

Ao longo da história, os equinócios foram fenômenos festejados e ligados
aos costumes de muitos povos. Um exemplo é a páscoa, uma das principais
celebrações cristãs que se iniciava com a mudança de estação. E
esperamos que este movimento em relação a esta grande estrela seja um bom
motivo para produzirmos conteúdo!

Para este equinócio o tema escolhido foi desenvolvimento web utilizando a
linguagem Perl. Gostaria de agradecer aos autores dos artigos, aos membros da
comunidade da São Paulo Mongers e outros grupos, como a Rio-PM e Brasil-PM.

Boa diversão, e aproveitem!

I<Thiago Rondon>, B<São Paulo Perl Mongers>.

=cut

