=pod

r2 - 20 Aug 2006 - JoenioCosta

=head1 Interagindo com interfaces Web

I<>

Quem nunca precisou recuperar uma informaE<ccedil>E<atilde>o da WEB, ou
simplesmente desejou criar uma ferramenta para agilizar uma tarefa do
seu dia a dia!?!

Essa pergunta E<eacute> um tanto generalizada! Mas... VocE<ecirc> que
tem interesse em fazer com que seu script adquira
informaE<ccedil>E<otilde>es contidas em um site especifico ou quer
agilizar uma tarefa rotineira que necessita interagir com sites web,
mas se depara com controles de usuE<aacute>rios, cookies,
seE<ccedil>E<otilde>es, ou seja, coisas que de certo modo dificulta o
seu objetivo...

Este pequeno artigo irE<aacute> lhe mostrar, acredito eu, o melhor
caminho para interagir com um site web que necessite dessas
operaE<ccedil>E<otilde>es.

=head2 1. IntroduE<ccedil>E<atilde>o

A idE<eacute>ia deste artigo E<eacute> lhe mostrar os mE<oacute>dulos
em Perl disponibilizados no CPAN que possibilitam efetuar cada
operaE<ccedil>E<atilde>o citada anteriormente (forms, cookies e
seE<ccedil>E<otilde>es) de uma maneira bem simples e sem muito
esforE<ccedil>o.

=head2 2. Forms

...

=head2 3. Controlando Cookies

...

=head2 4. Controlando SeE<ccedil>E<otilde>es

...

=head2 5. ConclusE<atilde>o

...

=head2 6. ReferE<ecirc>ncias

...

----

Criada por: frighetti E<uacute>ltima modificaE<ccedil>E<atilde>o em:
TerE<ccedil>a-feira 24 of Janeiro, 2006 [23:30:19 UTC] por frighetti

=cut

#Pod::HTML2Pod conversion notes:
# 1813 bytes of input
#Mon Dec 14 02:15:39 2009 mantovani
# No a_name switch not specified, so will not try to render <a name='...'>
# No a_href switch not specified, so will not try to render <a href='...'>
