=pod

r7 - 17 Nov 2006 

=head1 Variáveis Especiais em Perl

I<>

Guia de referE<ecirc>ncia rE<aacute>pida para as variE<aacute>veis
especiais do Perl

----

=over

=item * C<B<$_>>

VariE<aacute>vel padrE<atilde>o ou implE<iacute>cita

=back

=over

=item * C<B<@_>>

ParE<acirc>metros passados a uma subrotina

=back

=over

=item * C<B<$a,$b>>

VariE<aacute>veis usadas pela rotina C<sort()>

=back

=head2 ExpressE<otilde>es Regulares

=over

=item * C<B<$E<lt>dE<iacute>gitosE<gt>>>

Armazenador de padrE<otilde>es entre parE<ecirc>nteses C<($1, $2, ...)>

=back

=over

=item * C<B<$&>>

ContE<eacute>m a string encontrada pelo padrE<atilde>o

=back

=over

=item * C<B<$`>>

ContE<eacute>m a string que precedeu a encontrada pelo padrE<atilde>o

=back

=over

=item * C<B<$'>>

ContE<eacute>m a string que sucedeu a encontrada pelo padrE<atilde>o

=back

=over

=item * C<B<$+>>

ContE<eacute>m a string encontrada dentro do E<uacute>ltimo
parE<ecirc>ntesis aberto

=back

=over

=item * C<B<$^N>>

ContE<eacute>m a string encontrada dentro do E<uacute>ltimo
parE<ecirc>ntesis fechado

=back

=over

=item * C<B<@->>

contE<eacute>m a posiE<ccedil>E<atilde>o do inE<iacute>cio dos termos
da E<uacute>ltima comparaE<ccedil>E<atilde>o bem sucedida

=back

=over

=item * C<B<@+>>

contE<eacute>m a posiE<ccedil>E<atilde>o do final dos termos da
E<uacute>ltima comparaE<ccedil>E<atilde>o bem sucedida

=back

=over

=item * C<B<$*>>

TODO

=back

=over

=item * C<B<$^R>>

TODO

=back

ObservaE<ccedil>E<atilde>o: usar C<$&>, C<$`> e C<$'> em seus programas
prejudica a performance dos mesmos.

=head2 I/O e Separadores

=over

=item * C<B<$.>>

NE<uacute>mero da linha (ou entrada) atual do FILEHANDLE mais recente

=back

=over

=item * C<B<$/>>

Separador para entradas. "novalinha" por padrE<atilde>o

=back

=over

=item $|

Indica se deve ou nE<atilde>o fazer "flush" apE<oacute>s cada
operaE<ccedil>E<atilde>o de escrita. PadrE<atilde>o E<eacute>
nE<atilde>o (0).

=back

=over

=item $,

Indica um separador opcional de campos para o print

=back

=over

=item $\

Indica separador de saE<iacute>das, a ser incluE<iacute>do no final de
cada print.

=back

=over

=item $"

Indica separador de E<iacute>tens de uma lista, quando entre aspas.
PadrE<atilde>o E<eacute> " " (espaE<ccedil>o).

=back

=over

=item $;

Use listas multidimensionais ao invE<eacute>s disso.

=back

=head2 FormataE<ccedil>E<atilde>o

=over

=item $#

Formato da saE<iacute>da de nE<uacute>meros. PadrE<atilde>o E<eacute>
"%.ng".

=back

=over

=item $%

TODO

=back

=over

=item $=

TODO

=back

=over

=item $-

TODO

=back

=over

=item $~

TODO

=back

=over

=item $^

TODO

=back

=over

=item $:

TODO

=back

=over

=item $^L

TODO

=back

=over

=item $^A

TODO

=back

=head2 Avisos

=over

=item $?

TODO

=back

=over

=item $!

TODO

=back

=over

=item %!

TODO

=back

=over

=item $^E

TODO

=back

=over

=item $@

TODO

=back

=head2 ID's e InformaE<ccedil>E<otilde>es do Processo

=over

=item $$

NE<uacute>mero identificador do processo (PID)

=back

=over

=item $E<lt>

Identificador do usuE<aacute>rio real (UID)

=back

=over

=item $E<gt>

Identificador do usuE<aacute>rio efetivo (EUID)

=back

=over

=item $(

Identificador do grupo real (GID)

=back

=over

=item $)

Identificador do grupo efetivo (EGID)

=back

=over

=item $0

Nome do programa (nome do arquivo em execuE<ccedil>E<atilde>o)

=back

=over

=item $^O

Nome do sistema operacional

=back

=head2 InformaE<ccedil>E<otilde>es do Perl

=over

=item $]

A versE<atilde>o do Perl, para as versE<otilde>es anteriores a 5.6.x,
Utilize o $^V no lugar dessa variE<aacute>vel depois da versE<atilde>o
5.6.x.

=back

=over

=item $^C

TODO

=back

=over

=item $^D

TODO

=back

=over

=item $^F

TODO

=back

=over

=item $^I

TODO

=back

=over

=item $^M

TODO

=back

=over

=item $^P

TODO

=back

=over

=item $^R

TODO

=back

=over

=item $^S

TODO

=back

=over

=item $^T

contE<eacute>m o tempo do inE<iacute>cio da execusE<atilde>o do
programa em segundos (comeE<ccedil>ando em 1970)

=back

=over

=item $^V

versE<atilde>o e/ou revisE<atilde>o do interpretador Perl

=back

=over

=item $^W

TODO

=back

=over

=item $^X

TODO

=back

=head2 Argumentos da Linha de Comando

=over

=item ARGV

TODO

=back

=over

=item $ARGV

contE<eacute>m o nome do arquivo atual quando lido atravE<eacute>s do
operador E<lt>E<gt>

=back

=over

=item @ARGV

contE<eacute>m os argumentos passados pela linha de comando

=back

=over

=item ARGVOUT

TODO

=back

=head2 Diversos

=over

=item @F

TODO

=back

=over

=item @INC

contE<eacute>m os diretE<oacute>rios onde os comandos c, c e c
irE<atilde>o procurar por bibliotecas

=back

=over

=item %INC

TODO

=back

=over

=item %ENV

contE<eacute>m as variE<aacute>veis do ambiente

=back

=over

=item %SIG

TODO

=back

=over

=item $[

TODO

=back

=head2 AUTOR

Breno de Oliveira

=cut

#Pod::HTML2Pod conversion notes:
# 5640 bytes of input
#Sun Jan 31 01:45:47 2010 mantovani
# No a_name switch not specified, so will not try to render <a name='...'>
# No a_href switch not specified, so will not try to render <a href='...'>
